<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>AINoteSummarizer</RootNamespace>
    <UseFSharpPreview>true</UseFSharpPreview>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.1.3" />
    <PackageReference Include="Avalonia.Desktop" Version="12.1.3" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.3" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="12.1.3" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="Program.fs" />
    <AvaloniaResource Include="App.axaml" />
    <Compile Include="App.axaml.fs" />

    <AvaloniaResource Include="MainWindow.axaml" />
    <Compile Include="MainWindow.axaml.fs" />
  </ItemGroup>

</Project>
